### ISSUE TITLE
Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.

### ISSUE THREAD

**Issue by verwilst** [kontoulis/rabbitmq-laravel#2]
Switching to php-amqplib would be advisable i guess?

**Comment by kontoulis** [comment]
Use version dev-dev if it is allowed in your composer settings. It is using the php-amqplib. It is working but i didn't have time to finalize it, I use it on several production projects though.
"kontoulis/rabbitmq-laravel" : "dev-dev"

**Comment by verwilst** [comment]
Works! If you like it then you shoulda put a tag on it! :-)
