### ISSUE TITLE
Error Connecting to server (0): Failed to parse address \"<host>:tcp://172.17.0.5:4369\""

### ISSUE THREAD

**Issue by verwilst** [kontoulis/rabbitmq-laravel#3]
The host i put in config/rabbitmq-laravel.php seems to be appended by ':tcp://172.17.0.5:4369'. 

{
  "message": "Fatal error while initializing AMQP connection: Error Connecting to server (0): Failed to parse address \"<host>:tcp://172.17.0.5:4369\"",
  "status_code": 500,
  "debug": {
    "line": 94,
    "file": "/app/vendor/kontoulis/rabbitmq-laravel/src/Broker/Broker.php",
    "class": "Kontoulis\\RabbitMQLaravel\\Exception\\BrokerException",
....

Not sure where that comes from though.

**Comment by kontoulis** [comment]
Use version dev-dev if it is allowed in your composer settings. It is working but i didn't have time to finalize it, I use it on several production projects though.
"kontoulis/rabbitmq-laravel" : "dev-dev"

**Comment by verwilst** [comment]
dev-dev gives me:

{
  "message": "stream_socket_client(): unable to connect to tcp://my.rabbitmq.host:tcp://172.17.0.5:4369 (Failed to parse address &quot;my.rabbitmq.host:tcp://172.17.0.5:4369&quot;)",
  "status_code": 500,
  "debug": {
    "line": 134,
    "file": "/app/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php",

**Comment by kontoulis** [comment]
Can I see your config?

**Comment by verwilst** [comment]
conf/rabbitmq-laravel.php:

`<?php
/**
 * Package : RabbitMQ Laravel
 * User: kontoulis
 * Date: 12/9/2015
 * Time: 1:24 μμ
 */
return [
// AMPQ Connection settigns for RabbitMQ
	'amqp_host' => env('RABBITMQ_HOST', '127.0.0.1'),
	'amqp_port' => env('RABBITMQ_PORT', 5672),
	'amqp_user' => env('RABBITMQ_USER', 'guest'),
	'amqp_pass' => env('RABBITMQ_PASS', 'guest'),
	'amqp_vhost' => env('RABBITMQ_VHOST', '/'),
	'amqp_queue' => env('RABBITMQ_QUEUE', 'queue'),
];`

composer.json:

"require": { .... "kontoulis/rabbitmq-laravel" : "dev-dev" .... }

.env:
RABBITMQ_HOST=my.rabbitmq.host
RABBITMQ_USER=rmq
RABBITMQ_PASS=xxxxx
RABBITMQ_VHOST=/
RABBITMQ_QUEUE=myqueue.bleh

**Comment by verwilst** [comment]
my POST method does:

use Kontoulis\RabbitMQLaravel\Facades\RabbitMQ;
RabbitMQ::setMessage(json_encode([]));

**Comment by kontoulis** [comment]
Strange.
RABBITMQ_PORT is missing from .env , yet it is trying to connect at port 4369.
Can you try using IP address for rabbitmq host?

**Comment by verwilst** [comment]
Changing RABBITMQ_HOST to 127.0.0.1 gives me "unable to connect to tcp://127.0.0.1:tcp://172.17.0.5:4369".

**Comment by kontoulis** [comment]
In my eyes it seems like there is somewhere in .env 
RABBITMQ_PORT=tcp://172.17.0.5:4369
or something like that. 
set the .env 
RABBITMQ_PORT=5672
just in case

**Comment by verwilst** [comment]
Ok, this is strange..

Using 'amqp_port' => 5672 in rabbitmq-laravel.php works, as soon as i replace it to env('RABBITMQ_PORT', 5672), the error occurs. ( I've set RABBITMQ_PORT in my .env ).

**Comment by kontoulis** [comment]
Great, thank you I will look at it for the next release

**Comment by anirbanchakraborty123** [comment]
how to send message to queue.. how to set binding between exchange and queue..What to call?
